// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQjOV1szAvGUxEfYTYoV9tXuTY8Yj_Fs',
    appId: '1:262309608840:web:9d77c9c228d68ca9ebce3d',
    messagingSenderId: '262309608840',
    projectId: 'bikerider-22',
    authDomain: 'bikerider-22.firebaseapp.com',
    storageBucket: 'bikerider-22.appspot.com',
    measurementId: 'G-8CS4Z1FWSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjRsnPer-BqitgNY0zSNo9U9Ei96WRVaM',
    appId: '1:262309608840:android:9347347b06410fbdebce3d',
    messagingSenderId: '262309608840',
    projectId: 'bikerider-22',
    storageBucket: 'bikerider-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2D8QqO8hH0JpNFaUzayOvsCnnJkeJfXs',
    appId: '1:262309608840:ios:4fbedf1bf354bb1eebce3d',
    messagingSenderId: '262309608840',
    projectId: 'bikerider-22',
    storageBucket: 'bikerider-22.appspot.com',
    iosClientId: '262309608840-ndqk8u7tfq63avfpe5baut8j0ja389j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2D8QqO8hH0JpNFaUzayOvsCnnJkeJfXs',
    appId: '1:262309608840:ios:4fbedf1bf354bb1eebce3d',
    messagingSenderId: '262309608840',
    projectId: 'bikerider-22',
    storageBucket: 'bikerider-22.appspot.com',
    iosClientId: '262309608840-ndqk8u7tfq63avfpe5baut8j0ja389j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riderapp',
  );
}
